theme:
  name: material
  features:
      - navigation.sections  # Sections are included in the navigation on the left.
      - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
      - header.autohide  # header disappears as you scroll

site_name: PyDTS
site_description: The documentation for the PyDTS software library.
site_author: Tomer Meir, Rom Gutman

repo_url: https://github.com/tomer1812/pydts/
repo_name: tomer1812/pydts
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples_utils via symlink, so it's impossible for them all to be accurate

strict: false  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4  # Prevents h5, h6 from showing up in the TOC.

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



nav:
    - Home: 'index.md'
    - Introduction: intro.md
    - Methods:
      - Introduction: methodsintro.md
      - Definitions and Estimation: methods.md
      - Evaluation Metrics: methodsevaluation.md
    - Examples:
      - Event Times Sampler: EventTimesSampler.ipynb
      - Estimation Example:
        - Introduction: UsageExample-Intro.ipynb
        - Data Preparation: UsageExample-DataPreparation.ipynb
        - Estimation with TwoStagesFitter: UsageExample-FittingTwoStagesFitter.ipynb
        - Estimation with DataExpansionFitter: UsageExample-FittingDataExpansionFitter.ipynb
      - Data Regrouping Example: UsageExample-RegroupingData.ipynb
      - Comparing the Estimation Methods: ModelsComparison.ipynb
      - Evaluation: PerformanceMeasures.ipynb
      - Regularization: Regularization.ipynb
      - Small Sample Size Example: UsageExample-FittingTwoStagesFitterExact-FULL.ipynb
      - Screening Example: UsageExample-SIS-SIS-L.ipynb
      - Hospitalization LOS Simulation: SimulatedDataset.ipynb
    - API:
      - The Two Stages Procedure of Meir and Gorfine (2023) - Efron: 'api/two_stages_fitter.md'
      - The Two Stages Procedure of Meir and Gorfine (2023) - Exact: 'api/two_stages_fitter_exact.md'
      - Data Expansion Procedure of Lee et al. (2018): 'api/data_expansion_fitter.md'
      - Event Times Sampler: 'api/event_times_sampler.md'
      - Evaluation: 'api/evaluation.md'
      - Cross Validation: 'api/cross_validation.md'
      - Model Selection: 'api/model_selection.md'

plugins:
#  - mknotebooks
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          options:
            members: true
            show_inheritance: true
            inherited_members: true
            show_root_heading: true
            show_source: true
            merge_init_into_class: true
            docstring_style: google

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  copyright: Copyright &copy; 2022 Tomer Meir, Rom Gutman, Malka Gorfine
  analytics:
    provider: google
    property: G-Z0XYP3868P