name: Tests
on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.test-name }} (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.10","3.11","3.12","3.13"]
        test-name: [DataExpansionFitter, EventTimesSampler, TwoStagesFitter,
                    TwoStagesFitterExact, screening, model_selection, remaining]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry            # cache Poetry deps keyed by poetry.lock

      - uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: System deps
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Install project (with dev tools)
        run: poetry install --with dev --no-interaction

      - name: Run selected tests
        shell: bash
        run: |
          case "${{ matrix.test-name }}" in
            DataExpansionFitter) path="tests/test_DataExpansionFitter.py";;
            EventTimesSampler)   path="tests/test_EventTimesSampler.py";;
            TwoStagesFitter)     path="tests/test_TwoStagesFitter.py";;
            TwoStagesFitterExact) path="tests/test_TwoStagesFitterExact.py";;
            screening)           path="tests/test_screening.py";;
            model_selection)     path="tests/test_model_selection.py";;
            remaining) path="tests \
              --ignore=tests/test_DataExpansionFitter.py \
              --ignore=tests/test_EventTimesSampler.py \
              --ignore=tests/test_TwoStagesFitter.py \
              --ignore=tests/test_TwoStagesFitterExact.py \
              --ignore=tests/test_screening.py \
              --ignore=tests/test_model_selection.py";;
          esac
          poetry run pytest $path -v
