name: Tests
on: [push, pull_request]
jobs:
  test-DataExpansionFitter:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest tests/test_DataExpansionFitter.py -v

  test-EventTimesSampler:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest tests/test_EventTimesSampler.py -v

  test-TwoStagesFitter:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest tests/test_TwoStagesFitter.py -v

  test-TwoStagesFitterExact:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest tests/test_TwoStagesFitterExact.py -v

  test-screening:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest tests/test_screening.py -v

  test-model-selection:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run pytest tests/test_model_selection.py -v

  test-remaining:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          pip install poetry
          poetry install
      - name: Run remaining tests
        run: |
          poetry run pytest tests/ \
            --ignore=tests/test_DataExpansionFitter.py \
            --ignore=tests/test_EventTimesSampler.py \
            --ignore=tests/test_TwoStagesFitter.py \
            --ignore=tests/test_TwoStagesFitterExact.py \
            --ignore=tests/test_screening.py \
            --ignore=tests/test_model_selection.py \
            -v

