name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install gettext (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y gettext
      - name: Install gettext (macOS)
        if: runner.os == 'macOS'
        run: brew install gettext
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest tests/

